apiVersion: v1
data:
  inputFile: |
    1,20789
    2,1407
    3,23357
    4,12281
    5,9157
    6,27344
    7,9688
    8,9550
    9,13305
    10,12444
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.pod.namespace }}
