apiVersion: v1
data:
  gencsv.sh: |
    #!/bin/bash
    mkdir -p /csvserver/
    END=$1
    if [ $# -eq 0 ]
      then
        #echo "No arguments supplied, setting default as 10"
        END=10
    fi
    cat /dev/null >> /csvserver/inputdata
    for ((i=1;i<=END;i++)); do
        echo $i,$RANDOM | tee >> /csvserver/inputdata
    done
kind: ConfigMap
metadata:
  name: gencsv
  namespace: default
