apiVersion: v1
kind: Pod
metadata:
  labels:
    run: {{ .Values.pod.name }}
  name: {{ .Values.pod.name }}
  annotations:
    prometheus.io/scrape: "{{ .Values.annotations.scrape }}"
    prometheus.io/path: "{{ .Values.annotations.path }}"
    prometheus.io/port: "{{ .Values.annotations.port }}"
spec:
  containers:
  - image: {{ .Values.image.repository }}
    name: {{ .Values.pod.name }} 
    env:
      - name: {{ .Values.env.name }}
        valueFrom:
          secretKeyRef:
            name: {{ .Values.secret.name }}
            key: {{ .Values.env.name }}
    ports:
    - containerPort: {{ .Values.service.port }}
    volumeMounts:
      - name: {{ .Values.mountpath.volname }}
        mountPath: {{ .Values.mountpath.name }}
        subPath: {{ .Values.mountpath.filename }}
  volumes:
    - name: {{ .Values.mountpath.volname }}
      configMap:
        name: {{ .Values.configmap.name }}
