apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: csv-server
    app.kubernetes.io/managed-by: Helm
    release: prometheus
  name: prometheus-kube-prometheus-csv-server
  namespace: default
spec:
  endpoints:
  - port: http-metrics
    path: /metrics
    scrapeTimeout: 3s
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: csv-server
      app.kubernetes.io/managed-by: Helm
