apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "{{ .Values.annotations.scrape }}"
    prometheus.io/path: "{{ .Values.annotations.path }}"
    prometheus.io/port: "{{ .Values.annotations.port }}"
  labels:
    app: {{ .Values.deployment.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.deployment.name }}
