apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deployment.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.deployment.name }}
